# Generated by Django 5.0 on 2023-12-26 21:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(blank=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de CPF inválido', regex='^(\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}|\\d{11})$')], verbose_name='CPF')),
                ('phone', models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message='Formato de Telefone inválido. Ex (22) 99876-9999', regex='^(?:(?:\\+|00)?(55)\\s?)?(?:(?:(?:\\()?\\d{2}(?:\\)?)\\s?)?(\\d{4,5})[-.\\s]?(\\d{4}))$')], verbose_name='Telefone')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data Inicial')),
                ('duration', models.IntegerField(verbose_name='Dias de Duração')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('flag_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='hello.client', verbose_name='Cliente')),
            ],
            options={
                'ordering': ['-flag_active'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('domain', models.URLField(blank=True)),
                ('description', models.CharField(max_length=250)),
                ('keywords', models.CharField(max_length=200)),
                ('flag_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('clients', models.ManyToManyField(through='hello.Contract', to='hello.client', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Título')),
                ('url', models.URLField(verbose_name='URL')),
                ('_click_count', models.IntegerField(default=0, verbose_name='Nº de Clicks')),
                ('flag_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='hello.page', verbose_name='Página')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='hello.page', verbose_name='Página'),
        ),
        migrations.AddField(
            model_name='client',
            name='pages',
            field=models.ManyToManyField(through='hello.Contract', to='hello.page', verbose_name='Páginas'),
        ),
    ]
