# Generated by Django 5.0 on 2023-12-23 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de CPF inválido', regex='^(\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}|\\d{11})$')], verbose_name='CPF'),
        ),
    ]
