# Generated by Django 5.0 on 2023-12-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_client_cpf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='click_count',
            new_name='_click_count',
        ),
    ]
